Updated pre-commit-hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,22 +3,15 @@
 
 echo 'Performing code styling, testing, and building processes before committing'
 
-# Check Prettier standards
-npm run format:check ||
-(
-    echo 'Prettier Check Failed. Run npm run format:fix, apply the necessary changes, and try committing again.';
-    false;
-)
-
 # Check ESLint Standards
-npm run lint ||
+yarn run lint ||
 (
-        echo 'ESLint Check Failed. Review the listed issues, make the required adjustments, add the changes, and attempt to commit again.'
+        echo 'ESLint Check Failed. Run yarn run lint:fix, Review the listed issues, make the required adjustments, add the changes, and attempt to commit again.'
         false; 
 )
 
 # Check tsconfig standards
-npm run typecheck ||
+yarn run typecheck ||
 (
     echo 'The TypeScript configuration check has failed. Address the outlined issues above.'
     false;
@@ -27,7 +20,7 @@ npm run typecheck ||
 # If everything passes... Now we can commit
 echo 'The code appears to meet the required standards. Proceeding with the build process.'
 
-npm run build ||
+yarn run build ||
 (
     echo 'The Next.js build process encountered errors. Refer to the error messages above for troubleshooting steps.'
     false;
